### ISSUE TITLE
Move to self hosted dictionary endpoint

### ISSUE THREAD

**Issue by capJavert** [capJavert/clippy#18]
Move to new http://clippy-dictionary.kickass.website endpoint.

Waiting for https://github.com/capJavert/clippy-dictionary/pull/5

**Comment by Khazbs** [comment]
Right now Clippy does not say anything! What are you having trouble with?

**Comment by capJavert** [comment]
You need to replace endpoint from which clippy fetches comments to one mentioned in this issue. Look at https://github.com/capJavert/clippy/blob/master/src/state.js .

**Comment by Khazbs** [comment]
Is it possible to update the extension so that everyone gets it working? Replace the endpoint there or maybe even extract the endpoint location as a configurable browser extension setting?

**Comment by capJavert** [comment]
The idea is that other people can contribute through dictionary repository https://github.com/capJavert/clippy-dictionary. 

Your idea to make it configurable is also great and I like it so you are welcome to do a PR for this feature and we can ipdate the extension on firefox/chrome/opera stores afterwards.

Let me know if you are open to doing it :)

**Comment by Khazbs** [comment]
My initial idea is to make it work at least... I honestly have never worked on a browser extension and don't know how to package and publish them. My point is that Clippy doesn't say anything right now, which is why the extension is receiving most of its low ratings. If the problem is in replacing the endpoint, then could we replace it so you could update the extension in the store pretty please?
